[package]
name = "masm"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.7"
memmap = { version = "0.7.0", optional = true }
region = "2.2.0"
libc = { version = "0.2" }
errno = "0.2"
bitfield = "0.13.2"
[features]
selinux-fix = ['memmap']
default = []
