[package]
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"
name    = "masm"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
capstone = "0.7"
errno    = "0.2"
libc     = { version = "0.2" }
memmap   = { version = "0.7.0", optional = true }
region   = "2.2.0"
lazy_static = "1.4"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }

[features]
default     = []
selinux-fix = ['memmap']
